site_name: OmniBox Documentation
site_description: Documentation for the OmniBox 3D printer electronics case.
site_author: Jon Harper
site_url: https://jon-harper.github.io/OmniBox
repo_url: https://github.com/jon-harper/OmniBox
repo_name: jon-harper/OmniBox
edit_uri: ""
copyright: Copyright &copy; 2022 Jonathan Harper

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      auto_append: 
        - include/git_links.md
        - include/bom_links.md
        - include/other_links.md
        - include/contrib_links.md
        - include/abbrev.md
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  custom_dir: overrides
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.footer
    
  font:
    text: Noto Sans
    code: Source Code Pro
  palette: 
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: teal
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to light mode

plugins:
  - mike:
      canonical_version: latest
      alias_type: copy
  - search
  - macros:
      module_name: "src"

extra:
  version:
    provider: mike
  social:
    - icon: simple/discord
      link: https://discord.gg/nKmJZMhfz5
      name: OmniBox Discord Server
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/jonspaceharper
      name: u/jonspaceharper on Reddit
    - icon: simple/kofi
      link: https://ko-fi.com/jonspaceharper
      name: Support me on Ko-Fi!
  meta:
    version: 0.9.10 (Beta)
    this_branch: https://github.com/jon-harper/OmniBox/tree/0.9.10-beta/
    test_branch: https://github.com/jon-harper/OmniBox/tree/unstable/
    bom_files: 
        - assets/yaml/fastener.yaml
        - assets/yaml/bom.yaml
    product_file: assets/yaml/products.yaml

extra_css:
  - assets/stylesheets/extra.css
      
nav:
  - index.md
  - tour.md
  - development.md
  - license.md
  - printing.md
  - bom.md
  - Product Support:
    - support/index.md
    - support/panel_mounts.md
    - Supported Parts:
      - support/mcu.md
      - support/cpu.md
      - support/psu.md
      - support/displays.md
      - support/fans.md
      - support/lower_bay.md
  - Assembly Guide:
    - assembly/index.md
    - Heat Set Inserts (HSI):
      - assembly/hsi_tips.md
      # - assembly/hsi_base.md
      # - assembly/hsi_front.md
      # - assembly/hsi_rear.md
    - Core & PSU:
      - assembly/base.md
      - assembly/psu_wiring.md
      - assembly/core.md
    - CPU and Lower Bay Trays:
      - assembly/cpu.md
      - assembly/lower_bay.md
      - assembly/side.md
      - assembly/front.md
    - MCU & Panels:
      - assembly/mcu.md
      - assembly/rear.md
      - assembly/display.md
      - assembly/bottom_lid.md
  - Version History:
    - history/index.md
    - Prior Releases:
      - history/v0.9.9.md
      - history/v0.9.8.1.md
      - history/v0.9.8.md
      - history/v0.9.7.md
      - history/v0.9.5.md
      - history/v0.9.md